### ISSUE TITLE
OSF Alternative Color Could Be Improved

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf-style#10]
The Alternate Green color (#B8ECBF) is not a nice shade, and does not match the bootstrap colors used in other parts of the site.

**Comment by brianjgeiger** [comment]
Whaaa? I totally picked that color out of like, two colors.

**Comment by billyhunt** [comment]
This color would make Brian's color GREEN with envy!    Get it?  green . . . .
(crickets chirping)

(#c7ffc7)
![screen-shot-2015-06-09-at-4 22 32-pm](https://cloud.githubusercontent.com/assets/6232068/8068994/85628fdc-0ec5-11e5-9ba4-db6a4c2ea58d.png)

Or we could use the background color of our alert message to make the site more consistant.  

(#dff0d8)
![alternate-alternate-alternate-color](https://cloud.githubusercontent.com/assets/6232068/8069021/ab2d9e0a-0ec5-11e5-85b6-5d1ce12be4e5.png)

**Comment by brianjgeiger** [comment]
I like the top one better than the bottom one, at least when seeing them both together. It might be a good idea to have the alert on the screen at the same time, though, and maybe changing the alert color.

**Comment by caneruguz** [comment]
Thanks for the comments, this is why we have this common documen. I'm adding a discuss tag so we can talk through it. 

The green does not need to be in the same shades as alerts but the main idea is to work well in contrast with the blues all around that we are using. 

I also like the first shade, so if people agree we can go with that.

**Comment by jlcohoon** [comment]
+1 first shade!

**Comment by caneruguz** [comment]
The recommended new color is now applied to the style guide with this commit (https://github.com/CenterForOpenScience/osf-style/commit/b06c2bc414506b685fbfa1cffaa472fbf340f6df)
