### ISSUE TITLE
Suggestion: Add guideline for confirming dangerous actions

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf-style#34]
I suggest documenting what UI to use when confirming dangerous actions, e.g. deleting a project, registering a project.

**Comment by caneruguz** [comment]
http://caneruguz.github.io/osf-style/#feedback is trying to tackle some of this, there can probably be another row that talks about dangerous actions. Can you define dangerous actions a bit more though? Something like "Actions that will make irreparable changes to core project or user pages"

**Comment by sloria** [comment]
This isn't necessarily about feedback; it's more about preventing user error. Not sure if it belongs in that section.

In general, dangerous actions are rare, irreversible, and have some large impact.

For example, when you delete a project, a modal pops up prompting the user to enter a randomized string (a scientist's name).

We do something similar for registrations, requiring the user to enter the word "register" in a text input before submitting the form.

**Comment by caneruguz** [comment]
Added here: https://github.com/CenterForOpenScience/osf-style/commit/9d347d9da9f3744bae7520404a1bfa51e3d0b97c
