### ISSUE TITLE
Suggestion: Proper implementation of loading indicators

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf-style#39]
This may be outside the scope of these guides, but it would helpful for devs to know how to properly display a loading indicator for async actions.

**Comment by caneruguz** [comment]
What do you mean how to? Like how to implement the code? Where to put states and when to remove them etc?

**Comment by sloria** [comment]
Correct.

**Comment by caneruguz** [comment]
I don't think this is within the realm of this guide. It's more of a code guide and should be in the Dev Docs I think. I believe we need to separate style and ui how to and helpers from Front end Development coding help; they are undoubtedly very related but the goals of this guide and the common style are quite separate. I think Dev Docs is a better place for that.
