### ISSUE TITLE
Tooltip Mess up on UI guide page

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/osf-style#42]
### Steps
1. Open style guideline front pages
2. Click UI guide tab
Browser: Newest Chrome. 

### Issue
At the beginning, the tooltips hang in the middle of page and doesn't disappear.

![screen shot 2015-06-25 at 2 29 50 pm](https://cloud.githubusercontent.com/assets/5420789/8362447/d2d95d76-1b46-11e5-9f01-65e9fd53cc19.png)

**Comment by caneruguz** [comment]
https://github.com/CenterForOpenScience/osf-style/commit/03ee8adc1cf7bde21e52386e72bc4a663d6834f3
