### ISSUE TITLE
Add oxford comma rule to language

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf-style#43]
Add an item about using oxford comma in language section.

**Comment by sloria** [comment]
I was half-joking when I mentioned this on Flowdock, but the Elements of Style should be followed in matters of both style and grammar.

**Comment by caneruguz** [comment]
Part of this commit: https://github.com/CenterForOpenScience/osf-style/commit/4eaf732322b4d898378c386cdf4d84f467795896
