### ISSUE TITLE
Add use cases for links in Style Guide

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf-style#47]
##  Current State:

Currently, the style guide references the three kinds of links we use on the OSF but does not describe when we should use the different kinds of links.

![links](https://cloud.githubusercontent.com/assets/7093086/8532027/60266038-23f9-11e5-986a-dc9a3eee5f22.png)

##  Change to:

It would be helpful and more comprehensive to describe when the different kinds of links should be used.

**Comment by caneruguz** [comment]
Added here: https://github.com/CenterForOpenScience/osf-style/commit/f8e7ee12d2504d3928cb1a8f34428e9450fd60ae
