### ISSUE TITLE
Modal clarity

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf-style#48]
In the style guide you have an example for a modal:
![screenshot 2015-07-06 16 24 01](https://cloud.githubusercontent.com/assets/9381062/8532330/6eebf25c-23fb-11e5-84c1-4dad3f30e133.png)

However, in this example you have the 'Save Changes' button as blue.

This is contradictory to another place in the style guide:
![screenshot 2015-07-06 16 25 41](https://cloud.githubusercontent.com/assets/9381062/8532365/af763436-23fb-11e5-8e0f-71760f152edb.png)
Here you indicate that Saving and adding buttons should be green.

**Comment by caneruguz** [comment]
Changed here: https://github.com/CenterForOpenScience/osf-style/commit/0278fca843510eb3f3ad403e2940bd3306048214
