### ISSUE TITLE
Button Placement Consistency in Style Guide

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf-style#51]
Our site needs to be consistent for our users.  
Especially as users become depth users, they become accustomed to button placement for actions, e.g. all cancel/close buttons being on the left and accepting/confirming a change or action buttons on the right.  Currently there are buttons placed in inconsistent order across the site.
Button placement is not mentioned thus far in the style guide.

**Comment by caneruguz** [comment]
Changed here: https://github.com/CenterForOpenScience/osf-style/commit/87b34b89de34e9eb8deca82f8e43fd3af2e0bda7
