### ISSUE TITLE
Add "Apply" to the button color section

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf-style#52]
In the style guide, "Apply" is referred to in the chart below. However, it is not included in the button section where button colors are specified. Assigning it a color (blue?) in the chart will be clearer. Also, the chart says that it should be used for applying settings, like for add-ons. However, up till now, we've had **green** Submit buttons in add-on sections. To be consistent, we should decide on a color (otherwise, going with a green "Save" makes sense for add-on settings).

![applybutton](https://cloud.githubusercontent.com/assets/7093086/8578014/2455244a-257a-11e5-82b6-86134001ba9b.png)

![buttoncolors](https://cloud.githubusercontent.com/assets/7093086/8578149/10b56f2a-257b-11e5-8364-6434498b0e39.png)

**Comment by NatashaRichter** [comment]
I see that there's now a green "Apply" for add-on settings. Thanks @haoyuchen1992 
Perhaps we can still add the button to the color chart. Otherwise, looking good now!

**Comment by caneruguz** [comment]
Changed here: https://github.com/CenterForOpenScience/osf-style/commit/04947cc09f8d307a6127f3c2a899087a9a6c9059
