### ISSUE TITLE
Update language in the UI Guide

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf-style#54]
Update the language in the "Buttons and Toggles" section of the UI guide, as "Submit" buttons are still referred to here:

## Screenshot

![update_language_submit](https://cloud.githubusercontent.com/assets/7093086/8605853/fc5e9f7a-2655-11e5-98c5-2d611845f0fe.png)

**Comment by caneruguz** [comment]
Changed here: https://github.com/CenterForOpenScience/osf-style/commit/b0837b9e95325b03371ffda3c69c40ee7722e7aa
