### ISSUE TITLE
Create a class for word-break

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/osf-style#56]
Remember to create a class for word-break and replace the [code](https://github.com/CenterForOpenScience/osf.io/pull/3568/files#diff-a0d9bbd9f7565f8793a8e9f9b088246cR114)

Related to link: https://css-tricks.com/almanac/properties/w/word-break/

**Comment by haoyuchen1992** [comment]
Partial Summary --
More detailed explanation for css-tricks method -- https://kenneth.io/blog/2012/03/04/word-wrapping-hypernation-using-css/

However, I found a issue that if we apply css-tricks method, in a same paragraph, sometimes the word break would add hyphens but some not. Which is a big inconsistence. So I suggest to not use hyphens in our case and remain .  See the example below-- [jsfiddle link](http://jsfiddle.net/hw4r90zo/2/):
![screenshot 2015-07-29 11 01 38](https://cloud.githubusercontent.com/assets/5420789/8962671/c5487a3a-35e9-11e5-85f3-89d4e2e98a29.png)

As for word-wrap, it can make a new line when coming across a new word. 
More details see [StackOverflow discussion](http://stackoverflow.com/questions/1795109/what-is-the-difference-between-word-break-break-all-versus-word-wrap-break)
![screenshot 2015-07-29 12 05 25](https://cloud.githubusercontent.com/assets/5420789/8962753/42868dd4-35ea-11e5-85ea-66c6353c82f7.png)

The different is not so big. Therefore,  there is no obvious need to replace word-break with word-wrap. So the overall suggestion is that only using the word-break. 

    -ms-word-break: break-all;
     word-break: break-all;
     /* Non standard for webkit */
     word-break: break-word;

**Comment by caneruguz** [comment]
Can you make a PR and apply it, check to see if it breaks anything and/or works in cases that we need.

**Comment by caneruguz** [comment]
Actually let's add a section to the UI about breaking long text.

**Comment by caneruguz** [comment]
Added in this commit: https://github.com/CenterForOpenScience/osf-style/commit/84b505cdd052234198f00cdaee250e65ae7f849b
