### ISSUE TITLE
Inconsistencies in Modal Title Text, Capitalization, and Punctuation

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf-style#61]
Modal title text is inconsistent across the site.
![screen shot 2015-07-08 at 9 24 22 am](https://cloud.githubusercontent.com/assets/7839433/8732438/73fa9104-2bcb-11e5-996f-fcfe9816cff8.jpg)
![screen shot 2015-07-08 at 9 24 30 am](https://cloud.githubusercontent.com/assets/7839433/8732440/7729a496-2bcb-11e5-94a2-7189db5c4380.jpg)
![screen shot 2015-07-16 at 2 21 22 pm](https://cloud.githubusercontent.com/assets/7839433/8732442/7ae1ca3c-2bcb-11e5-8d1a-a6be317e9429.png)
![screen shot 2015-07-16 at 3 09 16 pm](https://cloud.githubusercontent.com/assets/7839433/8732653/e7860800-2bcc-11e5-83ca-6df2ec4ae7c4.png)

There are no formal rules for this yet. I propose that modal headings be in title case and only include punctuation if they are questions.

I still have questions about what type of text modal headings should have.
* Should there ever be long sentences such as "This wiki page has been deleted", or should it just say "Wiki Deleted"?
* When should we use text describing the action and when should the text read "Warning"?
* How would one explain such rules?

**Comment by geeksnglitter** [comment]
Any opinions @caileyfitz, @GaryKriebel, @lbanner?

**Comment by GaryKriebel** [comment]
@caneruguz is there any sort of industry standard for this?

**Comment by lbanner** [comment]
What @GaryKriebel asks ^^ .... for my part, I'd suggest brief sentence form, as much text needed for clarity but no more, sentence cap only - unless title, no punctuation but for "?"

**Comment by caneruguz** [comment]
@GaryKriebel this is not an area I'm very knowledeable about and I think it's more in the realm of a "Style Guide" for literary/editorial issues. We need some research into this, which I think @geeksnglitter can do for us(?)

**Comment by geeksnglitter** [comment]
Well Apple uses Title case for titles and question marks at the end only if it's a question - as proposed. https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html (And not a place to look for inspiration, but Microsoft does the same - https://msdn.microsoft.com/en-us/library/bb158706.aspx).

While not explicitly stated, Google seems to have most of its warning titles in sentence case: https://www.google.com/design/spec/components/dialogs.html.

I can look into this further if desired.

**Comment by GaryKriebel** [comment]
I think those are enough to guide us.

**Comment by caileyfitz** [comment]
@natasharichter may also have opinions on this. I would say that we should default to what the bigger sites are doing. I like the brief text as modal titles.

**Comment by lbanner** [comment]
Good finds @geeksnglitter --- I prefer sentence case, but would not at all feel badly about following Apple's lead : )

**Comment by geeksnglitter** [comment]
I accidentally misrepresented apple. Here is the real policy -  for iOS at least.
![screen shot 2015-07-16 at 4 18 10 pm](https://cloud.githubusercontent.com/assets/7839433/8734190/5c38d4b2-2bd6-11e5-87f1-2188067fabdb.png)

I think it may be easier to go the sentence case all the time route - that way there isn't as much thinking involved.
