### ISSUE TITLE
Finalize the use of dates and times on OSF

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf-style#65]
This issue aims to discuss and finalize a standard for how to display dates and times in a way that fits with OSF and COS goals. The aim is to quickly come to a concensus based on prior discussion. 

Some previous discussion on this issue have been made here: 
https://github.com/CenterForOpenScience/osf.io/issues/668
https://github.com/CenterForOpenScience/osf.io/issues/3615

Please add your suggestions in this thread.

**Comment by fabianvf** [comment]
Also saw this stackexchange discussion: http://ux.stackexchange.com/questions/16095/how-to-display-date-and-time

**Comment by lbanner** [comment]
Brief summary of above noted discussions: 
-- This is current log format on OSF: 2015-07-09 11:35 AM
-- The same is being proposed in the 2nd PR above for naming/distinguishing Registrations: 2015-01-23 1:42 PM

For sake of consistency and clarity at this point, I am good :+1: with above ^^ proposed approach.

Ping: @jlcohoon @GaryKriebel @JeffSpies @bnosek

**Comment by bnosek** [comment]
Yes, assuming that it is local time using iso8601 and tool-tip for UTC (as is elsewhere), then go.

**Comment by JeffSpies** [comment]
+1 to Brian's comment.

**Comment by caneruguz** [comment]
Okay I'm closing this issue as finalized. There is an existing PR which I will merge to include this information.
