### ISSUE TITLE
Link text inconsistencies

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf-style#70]
**Related to #69**

## Steps

Head to User Settings > Account Settings and notice links on that page:

**All lowercase**

![all_lowercase](https://cloud.githubusercontent.com/assets/7093086/8935685/fe3d9132-351b-11e5-99b1-9e18acb9ff6e.png)

On the same page, scroll down to the Security Settings header and notice the link there:

**Title case**

![title_case_link](https://cloud.githubusercontent.com/assets/7093086/8935472/ebf15c8a-351a-11e5-9c11-d5a5702c7a9c.png)

Now, head to one of your projects and click the "Add Links" button. Notice the links in the modal that appears:

**Sentence case**

![sentence_case_links](https://cloud.githubusercontent.com/assets/7093086/8935450/db770454-351a-11e5-92c7-253575710203.png)

## Expected behavior

The case of all links across the site should match.

## Actual behavior

The case of links varies widely across the site.

**Comment by NatashaRichter** [comment]
@geeksnglitter @caileyfitz, @lbanner @caneruguz

**Comment by lbanner** [comment]
@geeksnglitter is going to be posting an issue or PR as proposal on these items -- a thank you to her for undertaking!

**Comment by caneruguz** [comment]
Closing as part of this issue: https://github.com/CenterForOpenScience/osf-style/issues/71
