### ISSUE TITLE
Capitalization inconsistancies accross the OSF

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf-style#71]
## The problem
I have been attacking the discrepancies between sentence and title case one style component at a time, but I think that we need to address the concept of sentence versus title case all in one issue. 
If we make certain decisions that larger elements being sentence case, it would be strange to have smaller elements stay title case.

Currently, most elements on the OSF are title case, but there are discrepancies in almost every situation.

Here are some of the discrepancies currently being discussed:
- Modal titles: https://github.com/CenterForOpenScience/osf-style/issues/61
- Buttons: https://github.com/CenterForOpenScience/osf-style/issues/69
- Links: https://github.com/CenterForOpenScience/osf-style/issues/70

## Basic arguments
Title Case
- Most of the OSF is already in title case
- More aesthetically pleasing

Sentence case
- Easier to read
- Easier to understand

--------------------------------------------
Here are a list of some of the elements we should discuss:
- Panels
- Buttons
- Links
- Input text (e.g. selects, checkboxes)

Elements that are not currently relevant, but could be discussed:
- Navigation bar (Currently all in title case)
- Project navigation bar (currently all tabs are one word)
- Alerts (not explicitly stated in SG, but these already seem to be pretty consistently sentence case)

We could follow Github's lead, which might be the simplest to follow (everything is sentence case), but there would be a lot to change on the OSF (even their navigation bar is in sentence case).

**Comment by geeksnglitter** [comment]
Examples of panel capitalization inconsistency: 
![screen shot 2015-07-28 at 1 43 46 pm](https://cloud.githubusercontent.com/assets/7839433/8943269/f60f1202-3547-11e5-9f6a-d377755ca78b.png)
![screen shot 2015-07-28 at 1 43 31 pm](https://cloud.githubusercontent.com/assets/7839433/8943247/dbd94344-3547-11e5-82fe-30a67e16a4de.png)

**Comment by geeksnglitter** [comment]
Opinions?
@caileyfitz @caneruguz @NatashaRichter @sloria

**Comment by caneruguz** [comment]
Thanks for putting all this together! I think we should go with this:

Title Case:
- Top Navigation (main OSF Navigation and Project Navigation)
- Page Titles (like wiki title, Getting Started etc. ) 

Sentence Case:
- Panel headings
- Buttons
- Form labels
- Modal Titles
- Links
- Alert headings

Other than this follow regular capiatlization rules for instance
- Person names in Title Case (i.e. Add Caner Uguz to this project?)
- Special places and names of institutions in Title Case 
- Quoted Titles of projects in Title Case (i.e Delete project "Depiction of Sharks in Psychology"?)

**Comment by caileyfitz** [comment]
+1 to @caneruguz's suggestions! I think they all make sense!

**Comment by NatashaRichter** [comment]
Looks good @caneruguz. Sentence case for placeholder text, too, right?

**Comment by sloria** [comment]
Thanks for being thorough with this, Lauren. 

I am a "go" on Caner's suggested changes above.

A matter of process: we are working on our process for reviewing and implementing broad changes like this; this issue, among others, help to identify areas for improvement. 

For the time being, @caneruguz and I will sign off on these issues. QA will look for inconsistencies with these guidelines during testing. In the interest of protecting their time, they do not need to sign off on these discussions, though they may suggest improvements to these guidelines as they find them.

@JeffSpies @GaryKriebel @lbanner Let's move forward to formalize this process.

**Comment by geeksnglitter** [comment]
Okay so a few clarifications...
For example on https://osf.io/getting-started/
Does this mean that secondary titles such as "Structuring your work" on the getting started page would be sentence case as well? I also assume tertiary titles such as "User profile" would be sentence case.

**Comment by lbanner** [comment]
:+1:

**Comment by caneruguz** [comment]
@geeksnglitter 
Yes placeholder text too. In future cases if in doubt then Sentence case. 
Also yes on titles. Main header (i.e. Page Title) in title case, others sentence case.

**Comment by geeksnglitter** [comment]
:+1:

**Comment by caneruguz** [comment]
Okay there are two steps after this:
1. Add this rule to Style Guide in Language section and make a PR @geeksnglitter can you do this? 
2. After Step 1, create an issue in osf.io about unifying capitalization across the site. Either @haoyuchen1992 or I can take it from there.
