### ISSUE TITLE
Appropriate use of the loading spinner

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf-style#81]
The loading spinner should be used with care. Considerations:
- Should we allow multiple loading spinners to be shown on a page (e.g. different widgets on an OSF project's Overview page)? 
- Are there alternative indicators to use in different contexts?

Once we decide these, let's add it to the style docs.

**Comment by caneruguz** [comment]
Sounds good @sloria , we should tag people who should be discussing these though, otherwise the issue will not evolve further.

**Comment by sloria** [comment]
You can always assume that you are welcome to the discussion =) . You and I are the ones signing off on these after all. 

Tagging @erinmayhood, as these issues fall into the purview of "product design".

**Comment by sloria** [comment]
A few recommendations:

- We should limit the use of the spinning logo to pages where *content* (as opposed to navigation and controls) dominates the page. Example: View file page; Wiki page
- The user should rarely see multiple spinning logos on the same page at once.

We need to be careful not to associate our logo with a negative experience (waiting).

**Comment by GaryKriebel** [comment]
>"We need to be careful not to associate our logo with a negative experience (waiting)."

Wise words.

**Comment by caneruguz** [comment]
This point is very valuable:
> "The user should rarely see multiple spinning logos on the same page at once."

 It shows that pages need to have a holistic approach to design. If we want a single loader then we require more communication between proposals. So my point is while we can put that sentence in the guide; we need to think about what process ensures that developers don't just throw it in there. Proposal reviewers need to be cognizant of this issue. 

What should be the loading feedback when multiple things have content loading asynchronously in the same page?

**Comment by sloria** [comment]
> It shows that pages need to have a holistic approach to design...we need to think about what process ensures that developers don't just throw it in there.

I agree. Developers should be reviewing their own work to ensure that any UI they add fits within its context. Functional, product, and code reviewers should also be aware of this.

> What should be the loading feedback when multiple things have content loading asynchronously in the same page?

Perhaps muted text, such as "Loading citations..."

**Comment by caneruguz** [comment]
@sloria in that case we have some loading feedback using osf loader and some using just text. Doesn't that create some problems about when a loading logo is actually needed? 

One solution is to not use osf logo as a loader at all and use unobstrusive inline loading indicators like this 
![ajax-loader](https://cloud.githubusercontent.com/assets/1314003/9360540/cae02d2c-4664-11e5-8b8d-31d08c960cb4.gif)
 or just text.

**Comment by erinmayhood** [comment]
@sloria and @caneruguz usability studies strongly discourage the use of a custom loaders such as logos because it creates negative associations of your site (as suggested above). 

It would be great to have a single loader on each page (spinner or what Caner suggests above). When a dev is working on a page, can it be their responsibility to always verify that one spinner appears?

Any page that has content loading at very different times should have a ticket created for a performance review. So the process would be this:

A dev works on a feature on a page that already has a spinner
Dev does their work AND does the work to make the 1 spinner goal happen
If the dev while working on a page sees a long wait time for any part of the page, they make a ticket for a performance improvement. 
While planning releases we add performance enhancements 

Is this realistic?

**Comment by caneruguz** [comment]
So far we have very few places that use a spinner and we can probably reduce that further and add some guidelines.

- Start by not using any loading gifs
- If load is taking more than 1 second we need to look into performance 
- If performance can't be improved (i.e. external servers not in our control like Add-ons) use spinner.

I'm having a hard time envisioning single spinner. 
- Does that cover the entire page? 
I  think we need content to be avilable if it's ready and not cover it up with a page while another content is loading.
- Does it not cover a page?
 In that case which one is worthy of showing the spinner and what is the other section showing?

**Comment by sloria** [comment]
Closing this for now. The spinner is deprecated, and the docs have been updated with new loading indicators.
